### ISSUE TITLE
LRScaf running slow

### ISSUE THREAD

**Issue by Lutri22** [shingocat/agisps#10]
Hi

I am trying to use LRAscaf with a draft assembly of an invertebrate species (1.3Gb) and ~30x coverage of NP reads. I used minimap to create .paf file but it seems LRScaff really slowed down after this message was printed out in the log file Original "Edges size: 155118.". Now the only thing what is changed during the last 2 days of running was that the triadlinks.info file became a bit bigger. Could you help me if it is normal and I should be patient with it or something went wrong? I also copy my script here just in case if I made a mistake. 

java -Xmx900G -jar LRScaf-1.1.6.jar -c Ef_wtdbg.ctg.fa -a test.paf -t mm -o scaff_test -p 16 --identity 0.1

Many Thanks 

Szabolcs

**Comment by shingocat** [comment]
Szabolcs,

After building edges phase, LRScaf is on the graph simplification which is in a single thread by far. It needs time to finish this task.   The running script is right. you should be patient for this.

Is the draft assembly fragmental? You could try to run the LRScaf with the parameter "miniCntLen <default: 200 bp>" to filter small contigs (such as <= 500 bp).

**Comment by Lutri22** [comment]
Hi, 

Sorry for bothering again, but it is still working on the same step (8 days and 10 hours). Is there any possibility to make it quicker somehow? My assembly is not really fragmented (N50: 120KB) and I do not have any contig whit <5Kb in length so I do not think that the filtering could help. 

Thanks 

Szabolcs

**Comment by Lutri22** [comment]
I have an update. I just got the following error "2019-04-01 02:58:04 [ ERROR ]  agis.ps.graph.DirectedGraph      null" but it is still running. Shall I cancel it or it is still fine?

**Comment by shingocat** [comment]
Szabolcs,

This exception is thrown on Graph Simplification. I had fixed some on 1.1.7 version. These kinds of exception do not affect the scaffolding procedure. You could be patient for this.

Mao
