### ISSUE TITLE
Long stretches of homopolymers 

### ISSUE THREAD

**Issue by francicco** [shingocat/agisps#11]
Hi,

The software works pretty well, but somehow for one of the genome, I'm working on generating very long stretches of homopolymers mainly Ts and As. It does that in many parts of the genome. To me this is not biological but are due to the pacbio reads, how can I avoid it?

Thanks
F

**Comment by shingocat** [comment]
Francicco,

The assembly for homopolymers reads could not be fixed if there are not unique tag on both ends.

**Comment by francicco** [comment]
Hi,

There are possible solutions?
Thanks

F

**Comment by shingocat** [comment]
Francicco,

I don't have any idea to solve the homopolymers assembly using PacBio long reads alone by far. 
Might be you could try to combine other information to fix it. 
Sorry.

**Comment by francicco** [comment]
I also have linked reads (10x), I'd like to understand if it is something biological or rather and artifacts of the pacbio data. Also, masking them as Ns doesn't seem a reasonable solution for me. What do you think? Does this homopolymer issue ever happen to you?

Thanks 
F

**Comment by shingocat** [comment]
Francicco,

If your linked-reads has unique tag sequences which you could use this information to estimate the length of homopolymer. If not, this problem is still not to be solved.

**Comment by francicco** [comment]
Hi @shingocat,

This might interest you: those homopolymers are not present in the raw PacBio reads. My thought is that they should be Ns but somehow LRscaf places As and Ts.

F

**Comment by shingocat** [comment]
Francicco,

There are two files named "paths.info" and "links.info". You could get the contigs and long-reads info of the homopolymer region. LRScaf will do an alignment of overlap region between contigs and use the consensus sequences. If long-reads bridge two contigs only Ns will fill in the gap. You could check whether the homopolymers region is from Contigs or long-reads.

**Comment by faguil** [comment]
Hi,

I am facing the same problem with homolopymers As and Ts in my output from LRScaf. I have checked the PacBio reads and those long stretches of homopolymers are not there. So, I think there's an issue with LRScaf on that matter. I will appreciate any help/advice on that matter in order to fix the LRScaf output.

Cheers,

**Comment by faguil** [comment]
@francicco did you find any solution to this problem? Any help/advice is really appreciated. 

Thanks in advance

**Comment by francicco** [comment]
Yes, i stopped using it.
Unfortunately

F

**Comment by faguil** [comment]
Thanks for your answer. Yeah it is unfortunate, this software looked promising, but its results are not reliable. 

Best,

**Comment by shingocat** [comment]
Hi faguil and francicco, 

Could you offered the raw reads and contigs on one of the regions you mentioned? I need to test and check what happened.
You could get raw reads ids and contigs ids information from links, edges and paths information file.
Thanks very much!

**Comment by amvarani** [comment]
Hi there,
I'm having the same problem here. The LRScaf output with a lot of homopolymers As and Ts. These do not exist in raw and corrected pacbio reads

**Comment by chocotwig** [comment]
Hi, please could you address the above issues? I am skeptical about using LRScaf until we can see more info on the above bugs. Thanks!

**Comment by shingocat** [comment]
Hi amvarani and chocotwig,

Could you offer the contigs and long reads over one of these issued regions. And I could check what happed in LRScaf.
my email is qinmao@caas.cn. 
Many Thanks.

**Comment by shingocat** [comment]
Hi Francicco, faguil,  amvarani and chocotwig,

Whether the contigs is scaffolds sequences provided to LRScaf? LRScaf only supported to scaffold contigs sequences nor scaffolds sequences. Pls check this. If yes, broken by N to produce contigs, then run alignment over these contigs and do scaffolding.  
I will try to update a new version to support scaffolding on scaffolds sequences later. 
Thanks.

**Comment by faguil** [comment]
In my case, I provided scaffolds sequences for the scaffolding step. This might be the reason for those homopolymers As and Ts. Unfortunately, I moved forward with my genome project and used another scaffolder software. I hope you can fix this issue because your software looks promising.

Best,

**Comment by amvarani** [comment]
I also provided scaffolds for the scaffolding step. But these were generated by bionano Hybrid Scaffold. I want to use LRscaf to improve this result.

**Comment by shingocat** [comment]
Hi Francicco, faguil, amvarani and chocotwig,

I have updated a new version of LRScaf (1.1.10) which supports the draft assemblies is scaffolds sequences. You could try to use this new version. And if there are any issues, pls feel free to contact me. Thanks.

**Comment by amvarani** [comment]
Hi @shingocat 
Thanks a lot for your attention to this issue. I have tested the new version and did not find anymore the previous problem (Long stretches of homopolymers). However, I did not test extensively, hope that this new version fix the problem for our colleagues too

**Comment by francicco** [comment]
Hi,

I'm testing the new vesion LRScaf-1.1.9, LRScaf-1.1.10 and LRScaf-1.1.11. Unfortuately no file is produced, only the draft_summary.info

```
2020-10-21 13:18:17 [ INFO ]  Launching...
2020-10-21 13:18:17 [ INFO ]  Build output folder successfully!
2020-10-21 13:18:17 [ INFO ]  Building output folder, elapsed time: 1 ms
2020-10-21 13:18:32 [ INFO ]  Reading contigs, elapsed times: 14371 ms
2020-10-21 13:18:51 [ INFO ]  Valid Aligned Records: 0
2020-10-21 13:18:51 [ INFO ]  Reading Aligned Records, elapsed time: 19131 ms
2020-10-21 13:18:51 [ INFO ]  Repeat count: 0
2020-10-21 13:18:51 [ INFO ]  Finding repeat, elapsed time: 0 ms
2020-10-21 13:18:51 [ INFO ]  Valid Links Acount: 0
2020-10-21 13:18:51 [ INFO ]  Building Link, elapsed time : 4 ms
2020-10-21 13:18:51 [ ERROR ]  PathBuilder ? The Edges could not be empty!
2020-10-21 13:18:51 [ INFO ]  Ending...
2020-10-21 13:18:51 [ INFO ]  Scaffolding elapsed time: 33 s.
```

this is the commandline:

java -jar LRScaf-1.1.9.jar -i 0.1 -c $GENOMEDIR/$ASSEMBLY.fasta -a $GENOMEDIR/$ASSEMBLY.PacBioHiFi.mmp2.paf -t mm -o $GENOMEDIR/$ASSEMBLY.LRScaf

Thanks
F

**Comment by amvarani** [comment]
Hi again
I'm using the LRScaf-1.1.11, and for another set of data, is still generating long stretches of NNs. In this case, the genome is highly heterozygous

**Comment by francicco** [comment]
NNs I guess are gaps, I wouldn't be surprised. What type of input file are you using?
F

**Comment by amvarani** [comment]
@francicco , the input is a set of scaffolds with Zero NNs. The output of LRScaf-1.1.11 is generating long stretches of NNs (>30kb), much larger than the reads used to scaffold

**Comment by shingocat** [comment]
> Hi,
> 
> I'm testing the new vesion LRScaf-1.1.9, LRScaf-1.1.10 and LRScaf-1.1.11. Unfortuately no file is produced, only the draft_summary.info
> 
> ```
> 2020-10-21 13:18:17 [ INFO ]  Launching...
> 2020-10-21 13:18:17 [ INFO ]  Build output folder successfully!
> 2020-10-21 13:18:17 [ INFO ]  Building output folder, elapsed time: 1 ms
> 2020-10-21 13:18:32 [ INFO ]  Reading contigs, elapsed times: 14371 ms
> 2020-10-21 13:18:51 [ INFO ]  Valid Aligned Records: 0
> 2020-10-21 13:18:51 [ INFO ]  Reading Aligned Records, elapsed time: 19131 ms
> 2020-10-21 13:18:51 [ INFO ]  Repeat count: 0
> 2020-10-21 13:18:51 [ INFO ]  Finding repeat, elapsed time: 0 ms
> 2020-10-21 13:18:51 [ INFO ]  Valid Links Acount: 0
> 2020-10-21 13:18:51 [ INFO ]  Building Link, elapsed time : 4 ms
> 2020-10-21 13:18:51 [ ERROR ]  PathBuilder ? The Edges could not be empty!
> 2020-10-21 13:18:51 [ INFO ]  Ending...
> 2020-10-21 13:18:51 [ INFO ]  Scaffolding elapsed time: 33 s.
> ```
> 
> this is the commandline:
> 
> java -jar LRScaf-1.1.9.jar -i 0.1 -c $GENOMEDIR/$ASSEMBLY.fasta -a $GENOMEDIR/$ASSEMBLY.PacBioHiFi.mmp2.paf -t mm -o $GENOMEDIR/$ASSEMBLY.LRScaf
> 
> Thanks
> F

Hi Francicco,

Long reads should be bridged two contigs/scaffolds sequences when doing scaffolding. Minimap might be yielded 1 vs 1 alignment using HIFI pacbio long reads.  Please check it first. if not, you could change the parameters for building links, such as overlap length, overhang length, identity, etc.  Since HIFI reads are more accurate than PacBio CLR reads which are for the design of LRScaf.

**Comment by shingocat** [comment]
@amvarani 
LRScaf does not do gap filling job. After the scaffolding step, gap would be filled with Ns.
