### ISSUE TITLE
LRScaf-1.1.8 stuck at "Finding repeats"

### ISSUE THREAD

**Issue by bvaldebenitom** [shingocat/agisps#14]
Hi!

I've been running LRScaf, and since yesterday it apparentely hasn't done anything. The last line of the log is:
`2020-01-04 17:27:40 [ INFO ]  Finding repeat, erase time: 1948 ms`
When using "top" the process appears with state S (interruptible sleep (waiting for an event to complete), https://idea.popcount.org/2012-12-11-linux-process-states/)

Any clue regarding this? How long should I expect this step to last? 

The minimap alignment file is a 4.1 Gb file, the contigs file is a 4.3 Gb file, and current memory usage of LRScaf seem to be ~16 Gb.

**Comment by shingocat** [comment]
Hi bvaldebenitom,

The next step is to build links from alignment after the finding repeat step. As you  stated, the alignment records are much large. It will take time to do that. You could try to use multi-threads to speed up this process.

**Comment by xiekunwhy** [comment]
LRScaf-1.1.9 stuck at "Finding repeats" too.

**Comment by shingocat** [comment]
hi xiekunwhy,

You could try to use multi-threads options or fliter the small contigs by minContiglenght option.
