### ISSUE TITLE
Composition of scaffolds ?

### ISSUE THREAD

**Issue by ptranvan** [shingocat/agisps#16]
Hi,

The program worked and I got scaffolds at the end. 

How can I get the information about which contigs on my asssembly have been assembled in which scaffolds ?
In other word: for one scaffold in particular I would like to know the name of the contigs scaffolded ?

thanks

**Comment by shingocat** [comment]
Hi, ptranvan,

In the output folder, there are a file named, nodePaths.info, including the information what you want.
