### ISSUE TITLE
Contig used more than once ?

### ISSUE THREAD

**Issue by ptranvan** [shingocat/agisps#18]
Hi, we found some contigs that were used more than once in the scaffolding. For instance `ctg015357` which is in scaffolds `G824` and `G7782`. 

`cat nodePaths.info `

```
digraph G824{
ctg038297->ctg044989->ctg015357->ctg028040->ctg034934->ctg075623->ctg055892->ctg000373;

digraph G7782{
ctg014392->ctg015357;


```

How is it possible and what is your interpretation about that ?

Thanks.

**Comment by shingocat** [comment]
Hi ptranvan,

By using read coverages information, LRScaf determine the repeat contigs or unique contigs. If it is the type of repeat contigs, it will use more than one in the graph travel.

**Comment by ptranvan** [comment]
Thanks @shingocat. 

It makes sense.  Is there any option to use a contig uniquely (even if it's a repeated one) ?

**Comment by shingocat** [comment]
Hi ptranvan,

There is no parameter for this purpose now.
