### ISSUE TITLE
args error

### ISSUE THREAD

**Issue by orangeSi** [shingocat/agisps#2]
when I use like this:
`java -jar target//LRScaf-1.1.2.jar --contig draft.fa -a test.m4 -t m4 --identity 0.8 --miniSupLinks 1 --output `, 
get this error:
`2018-07-30 13:52:24  [ main:0 ] - [agis.ps.Main.main(Main.java:67)] - [ ERROR ]  agis.ps.Main	The option 't' was specified but an option from this group has already been selected: 'a'`

**Comment by orangeSi** [comment]
the xml works well~

**Comment by shingocat** [comment]
orangeSi，
We have fixed the bug for parsing the command-line parameters.  The newest version of LRScaf-1.1.3 under the target folder had tested and worked on parsing the command-line parameters.
Recommend to use XML configure file.
 Thanks

**Comment by orangeSi** [comment]
thanks~
