### ISSUE TITLE
More duplication ?

### ISSUE THREAD

**Issue by ptranvan** [shingocat/agisps#22]
Hello,

Thanks for your software. I used LRScaf to scaffold my contig assembly. Here is the busco before and after LRScaf:

```
before: C:95.4%[S:94.7%,D:0.7%],F:1.3%,M:3.3%,n:1367
after: C:95.8%[S:91.4%,D:4.4%],F:1.2%,M:3.0%,n:1367
```

How can we explain the fact that there is more duplicated busco after ?

Thanks for your help.

**Comment by shingocat** [comment]
ptranvan,

LRScaf will connect two contigs if supported by long reads over your specified thresholds. And LRScaf will try to resolve the repeat contigs and keep it original copies in the assemblies.

**Comment by KyleEwart** [comment]
Hello,

I had the same issue:
before - 91.8%[S:90.9%,D:0.9%],F:5.0%,M:3.2%,n:1367
after - C:92.9%[S:81.5%,D:11.4%],F:3.6%,M:3.5%,n:1367

Was there any resolution on why there might be considerably more duplication after running LRScaf?

Thanks
