### ISSUE TITLE
nodePaths.info could not be created LRScaf-1.1.10

### ISSUE THREAD

**Issue by igorantoshechkin** [shingocat/agisps#23]
When I try using LRScaf v 1.1.10, I get a message 'The output file/mmjggl/nicodemus/.../nodePaths.info could not be created!'. The nodePaths.info file is actually present in the output folder, but it is empty. The scaffolds.fasta seems to get generated correctly.

When I run exactly the same command using v 1.1.9, nodePaths.info gets properly generated. It seems like the changes introduced into the file writer in the new version broke it. I'm fine with using v 1.1.9, but wanted to let you know.

Also related to this, how can I translate the digraph IDs used in nodePaths.info (e.g. G1), into scaffold IDs (e.g. Scaffolds_0) used in scaffolds.fasta? I need this to figure out what contigs from the initial assembly ended up in LRScaf scaffolds.

Thanks!

**Comment by shingocat** [comment]
Hi igorantoshechkin,

Thanks for you information. The new version LRScaf v1.1.11 had fixed the bug on building node path information. The issue only affect the creation of nodepaths.info file.  The scaffolds is correct. 
On the nodepaths.info file, each record such as digraph G[num]{} is corresponding to the scaffold id in scaffolds.fasta file. The nodepaths.info could be directly used by dot graph cmd to build a SVG or png format. Each node in the digraph G[num]{} structure is the original contig and the suffix "_F" or "_R" of node is the strand of contig on the path.

**Comment by igorantoshechkin** [comment]
Thank you!
