### ISSUE TITLE
agis.ps.file.M4Reader error and PathBuilder error

### ISSUE THREAD

**Issue by wufabai** [shingocat/agisps#24]
I encountered issues like a few others reported before. I tried to use the various changes suggested by everybody in previously resolved issues, but kept getting the same error. 

This is what I did:
minimap2 -t 6 FW4911_contigsrenamed.fa ../FW4911nanopore_assemblies/FW4911nanoporeassembly1.fq -o ./FW4911spades_NPaln.mm; lrscaf -x FW4911ScafConf0.xml; (lrscaf was an alias: lrscaf="java -Xms100g -Xmx100g -jar /Path/to/LRScaf-1.1.11.jar")

This are the two errors I got:
[ ERROR ]  agis.ps.file.M4Reader    On lines: 1     For input string: "NODE_468_length_20536_cov_6283"
PathBuilder ： The Edges could not be empty!

I took a look at the first line of the .mm file, it is as below:
1f3d91e5-29eb-4a70-a5dc-4a8027c831ff    491     44      464     -       NODE_468_length_20536_cov_6283  20536   1158    1603    51      445     9   tp:A:P   cm:i:6  s1:i:46 s2:i:0  dv:f:0.1666     rl:i:0

Thank you in advance for your help!

**Comment by shingocat** [comment]
you should change to use "mm" tag for specified the output of minimap alignment on the configure.xml .  The "m4" tag is for blasr m4 format.
