### ISSUE TITLE
Can lrscaf accept 'scaffolds' as input instead of 'contigs'?

### ISSUE THREAD

**Issue by xiekunwhy** [shingocat/agisps#25]
Hi @shingocat ,

Two questions about lrscaf,
1) Can I use 'scaffolds' as input instead of 'contigs'? My draft assembly was generated from platanus-allee, and has been scaffolded by platanus-allee itself, but I want to try lfscaf to improve it. I know I could split scaffolds into contigs, but contigs are very very fragmented if I do so(several millions contigs may be), so I don't want to split the existing scaffolds.

2) If 'scaffolds' is acceptable by lrscaf, should I do gap close(13% N in my draft assembly) first or lrscaf first ?

Best,
Kun

**Comment by shingocat** [comment]
xiekunwhy,

The new version of LRScaf support the scaffolds as input. LRScaf do not do gap filling, you should do gap filling by other tools. You could try to do scaffolding first by LRScaf and then gap closing.
