### ISSUE TITLE
Parameters for contiguous assemblies

### ISSUE THREAD

**Issue by A-J-F-Mackintosh** [shingocat/agisps#27]
Hi,

I have assembled a genome from pacbio CLR reads, and the assembly is very contiguous (Span=407Mb, N50=12Mb). I want to try LRScaf to see whether there are any contigs that could be joined further. I realise that improvement will be limited, but it is possible that smaller overlaps (<1kb) will have been ignored in assembly and so the assembly could be improved by LRScaf.

Because some of the contigs in the assembly are very long, I thought it best to set `-mioll 300 -miolr 1e-100`, as even a 1kb overlap would be a tiny fraction of a 20Mb contig and so would be removed if `-miolr 0.8`.

There are some other parameter that I do not understand though, and so am not sure if/how to change them. In particular, what is the overhang length of a contig, and what is the end length of a read? Should I change these parameters (`-maohl -maohr -mael -maer`) and are there any others I should consider changing?

Best wishes,

Alex

**Comment by shingocat** [comment]
Hi Alex,

The assemblies are very contiguous, using the same long reads datasets might be not very informative on scaffolding procedure.  
The -mioll, -miolr, -maohl -maohr -mael and -maer are the filter and validation parameters for alignment records.  LRScaf uses long reads to bridge different contigs. A long read is divided into three parts by four points, i.e. P1-----P2----------P3-----P4, where the P1 and P4 are the long read start and ending point, the P2 and P3 are the point specified by mael or maer parameters. So the ending length of a read means the [P1, P2] and [P3, P4] regions. The overhang length of a contig means the un-alignment block of contig over long read. The alignment style likes ">----<". The overhang length is the un-alingment block length of contig. 
the miolr is functional when the alignment block of contig is on the [P2, P3] region. You could specified large mael, maer, maohl, maohr, and smaller mioll, such as mael 3000, maer 0.3, maohl 5000,  maohr 0.2, mioll 200. However, the loose parameters would make more false positive linkage.  
![bridging schema](https://user-images.githubusercontent.com/1930416/106844920-bfb7c300-66e4-11eb-83dc-83f357e3fa20.jpg)

**Comment by A-J-F-Mackintosh** [comment]
Hi,

Thank you for the explanation of the parameters - the drawing is particularly useful.

I have run LRScaf with a few different parameter combinations and think it provides some useful results.  It would be really handy to have a parameter which sets a minimum ratio of overlap to overhang. Currently it is possible to have an overlap just over the minimum length with an overhang just under the maximum, so only a small portion of the read is actually aligning. Maybe this could be implemented in a future release?

Anyway, thanks again for your help.

Alex
