### ISSUE TITLE
Inability to parse iqrt parameter

### ISSUE THREAD

**Issue by tararickman** [shingocat/agisps#28]
Hi @shingocat,

I have been able to successfully run lrscaf but am now encountering issues when iterating through different values for specific parameters. I am using a bash script to iterate through various values for specific parameters (ie: mioll, iqrt, mmcm) to assess which combination is optimal. 

contents of .sh script:
`#!/bin/bash
counter=0
declare -a mioll=("320" "960")
declare -a tl=("1000" "10000")
declare -a iqrt=("1.5" "3")
declare -a mmcm=("5" "10")
for i in "${mioll[@]}"
do
        for i in "${tl[@]}"
        do
                for i in "${iqrt[@]}"
                do
                        for i in "${mmcm[@]}"
                        do
                                let counter++
                                java -jar /pickett/software/lrscaf/LRScaf-1.1.11.jar \
-p 20 \
-c /path/to/Scaffolds.fasta \
-a /path/to/mapped.paf \
-t mm \
-mioll $mioll \
-tl $tl \
-iqrt $iqrt \
-mmcm $mmcm \
-o ./2_15_2021/$counter/output_species
            done
        done
    done
done`

The error I am getting is:
`2021-02-15 14:08:51  [ ERROR ]  Error:
java.lang.NullPointerException: Cannot invoke "String.trim()" because "in" is null
        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1838)
        at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.base/java.lang.Double.parseDouble(Double.java:549)
        at java.base/java.lang.Double.valueOf(Double.java:512)
        at agis.ps.Main.parsering(Main.java:291)
        at agis.ps.Main.main(Main.java:48)
2021-02-15 14:08:51  [ ERROR ]  agis.ps.Main    Cannot invoke "String.trim()" because "in" is null`

When I remove the variable iqrt and let it run default, the error goes away and lrscaf successfully runs. I tested out my script with just one value for each parameter to see if iqrt was having an issue with decimal (1.5) vs whole (3) numbers but regardless, the same error occurs.

Please let me know of any additional information you may need to help with this. Thank you!

**Comment by shingocat** [comment]
Hi taraickman,

Thanks for your reports. I had fixed the issues for parsing the iqrt value on command-line. you can try to use the new version 1.1.12 under the target folder.

**Comment by tararickman** [comment]
Thank you for working on this fix! Version 1.1.12 works as expected.
