### ISSUE TITLE
Nanopore alignment with PACBIO

### ISSUE THREAD

**Issue by khush876** [shingocat/agisps#31]
Hi, I have clean reads from PACBIO assembly generated from Hifiasm. Error correction and polishing is performed using RACON and PILON. This gave me good N50. However, when I aligned cleaned assembly to the reference genome (plant), the scaffolds are still not extended. 
After that I aligned my cleaned assembly to Nanopore (rawfile.fq) using MINIMAP2. I have .paf file as well .sam file after the alignment. Now I am not sure how to proceed with LRSCARF. Can you please suggest? I would appreciate that. 

Thank you

**Comment by shingocat** [comment]
Khush876,

It would be not very obvious to improve assembly contiguous by using nanopore reads to scaffold the pacbio assembly if the N50 of nanopore reads is not much larger than PacBio reads.
