### ISSUE TITLE
What does mmcm mean?

### ISSUE THREAD

**Issue by wangshun1121** [shingocat/agisps#5]
As introduced, **The parameter to filter invalid Minimap alignments. Default: <8>. Only for Minimap alignment.** Then I wonder by what level does LRScaf filter the alignment results? Mapping quality score?

Here is the definition of PAF files:

https://github.com/lh3/miniasm/blob/master/PAF.md

The 8th column is **Target start on original strand** and I wonder how can LRScaf filter alignments by this column. Should it be the last column, in 12-columned PAF file, should it be the 12th column **Mapping quality** ? 

Then what is the threshold of this vaule? >0? >10? or >30? Would you please show some more details?

**Comment by shingocat** [comment]
wangshun1121,

The mmcm is the abbreviation for Minimap CM Tag, which is  the number of minimizer
hits in a cluster.  LRScaf will filter the low CM value of alignment.  The default <8> is tested in most of our experiments, you could change it according to your case.
