### ISSUE TITLE
How to improve continuity of scaffolds?

### ISSUE THREAD

**Issue by wangshun1121** [shingocat/agisps#6]
手上有80x左右的pacbio，先前用[MeCAT](https://github.com/xiaochuanle/MECAT)组装出来一堆Contig，那么通过调整哪些参数，可以提高scaffold的连续性？可否有些建议呢？

**Comment by wangshun1121** [comment]
首先，默认参数运行LRScaf：
```
java -jar ~/lrscaf/target/LRScaf-1.1.5.jar -c ./Contigs.fasta -a ./Contigs.align.paf --type mm -o ./Default
```
考虑到默认的overlap为contig总长的80%，而我想提高三代contig的N50，所以，调整参数重跑：
```
java -jar ~/lrscaf/target/LRScaf-1.1.5.jar -c ./Contigs.fasta -a ./Contigs.align.paf --type mm -o ./Loose -miolr 0.001 -mmcm 12 -i 0.1
```
-miolr特地给了一个非常小的数值，毕竟Contig的N50已经160k了，若再延长N50，不得不将该值调的尽量小。-mmcm我设置为12，毕竟我的paf有12列且最后一列为比对分数。

然而，上述两个命令跑完，得到的Scafold的序列数目和总长居然一样。请问是何原因？

**Comment by shingocat** [comment]
wangshun1121,

-miolr specifies the overlap ratio of contig, alignment_length/contig_length. 
-mmcm specifies the CM Tag values of minimap. It will filter the alignment records lower than this values.

If you have such high coverage of TGS reads, you could try to correct the reads first. And then using the corrected reads to do pure TGS assembly or scaffolding.
And I suggest that you could adjust the min_contig_length and min_supported_links according to your final draft assemblies and the coverages of TGS reads.

Do you use the same TGS dataset to construct contigs and do scaffolding? If that is true, the improvement is limited.

**Comment by wangshun1121** [comment]
Actually, the shortest contig is over 10000bp. Then should I reduce the value of  min_supported_links? The corrected reads are about 40x against primary assembly.

**Comment by shingocat** [comment]
Wangshun1121,

Do you use the same TGS dataset to construct contigs and do scaffolding?

**Comment by wangshun1121** [comment]
Yea. Then I tried to use raw reads for scaffolding

**Comment by shingocat** [comment]
Wangshun1121,

I did not test the strategy for using the same TGS reads dataset on constructing contigs and scaffolding. LRScaf is used to improve the draft assemblies using TGS long reads, and the draft assemblies were constructed by NGS reads or other datasets. 
If you wanna use the same datasets for scaffolding, I thought the improvement would be limited.

**Comment by wangshun1121** [comment]
OK, perhaps I have got the key point
