### ISSUE TITLE
Error PathBuilder

### ISSUE THREAD

**Issue by MeiFangLin** [shingocat/agisps#8]
Hi there,

I am using Minimap2 (paf) file as the input (aligned file) to run lrscaf.
I got these errors
2019-03-12 14:40:44  [ ERROR ]  agis.ps.file.MMReader   For input string: "SN:scaffold1_cov25"
2019-03-12 14:40:44  [ ERROR ]  PathBuilder ： The Edges could not be empty!

It will be appreciated if you can let me know how to fix this problem.

Thank you,
Mei

**Comment by shingocat** [comment]
Mei, 

There are some problems for the string "SN:scaffold1_cov25".
Could you offer me some rows of your PAF file.
Thanks.

**Comment by MeiFangLin** [comment]
Hi,
Thank you for the reply. I found the problem here. I accidentally used bam file from Minimap2. I have used correct paf file, it works now.
Thanks,
Mei
