### ISSUE TITLE
[ ERROR ]  agis.ps.graph.DirectedGraph

### ISSUE THREAD

**Issue by MeiFangLin** [shingocat/agisps#9]
I used paf from minimap2 and got this error. 
2019-03-13 18:08:37  [ ERROR ]  agis.ps.graph.DirectedGraph     null

Although there were outputs generated, what does this error mean and how to fix it?

Thank you,
Mei

**Comment by shingocat** [comment]
Mei,

This will occur in the Graph simplification step since some nodes are simplified. And it will not affect the assembly outcome. 
I will update the statement on catching Exception in next version.
Thanks.

**Comment by MeiFangLin** [comment]
I see. Thank you very much.
